version: "3.9"

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    command: gunicorn main.wsgi:application --bind 0:8000
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
      - app


volumes:
  static_value:
  media_value:





