# Generated by Django 5.0.3 on 2024-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
